openapi: 3.0.0
info:
  title: monolith-microservice-shop
  version: 1.0.0
servers:
- url: /
paths:
  /orders:
    post:
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                product_id:
                  format: int64
                  type: integer
                address:
                  $ref: '#/components/schemas/_orders_address'
              required:
              - address
              - product_id
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: order has been created
  /orders/{id}/paid:
    get:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: status
components:
  requestBodies:
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    _orders_address:
      properties:
        name:
          type: string
        street:
          type: string
        city:
          type: string
        post_code:
          type: string
        country:
          type: string
      required:
      - city
      - country
      - name
      - post_code
      - street
      type: object
    inline_response_200_1:
      example:
        id: 0
        is_paid: true
      properties:
        id:
          format: int64
          type: integer
        is_paid:
          type: boolean
      type: object
    inline_object:
      properties:
        product_id:
          format: int64
          type: integer
        address:
          $ref: '#/components/schemas/_orders_address'
      required:
      - address
      - product_id
      type: object
    inline_response_200:
      example:
        order_id: 0
      properties:
        order_id:
          format: int64
          type: integer
      required:
      - order_id
      type: object
